version: '3.9'
services:
  php-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./vendor:/var/www/vendor 
      - ./resources:/var/www/resources
      # Exclude vendor folder from host
      #- /var/www/vendor
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      sh -c "docker-php-entrypoint apache2-foreground"